-- BETA: distingue si el pie de foto lo puso la identificación
-- automática (true) o el admin a mano (false, valor por defecto — así
-- nunca se arriesga un pie de foto ya existente al añadir esta columna).
ALTER TABLE "Photo" ADD COLUMN "descriptionAutoGenerated" BOOLEAN NOT NULL DEFAULT false;
