-- BETA: se simplifica "Identificar fotos ya subidas" para que regenere
-- TODAS las fotos sin condiciones, así que ya no hace falta distinguir
-- pie de foto manual de automático.
ALTER TABLE "Photo" DROP COLUMN "descriptionAutoGenerated";
